plugins {
  id 'java'
  id 'maven-publish'
  id 'com.enonic.xp.app'
}

repositories {
  mavenLocal()
  mavenCentral()
  xp.enonicRepo()
  maven { url 'https://repo.enonic.com/public' }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${group}"
            artifactId = "${projectName}"
            version = "${version}"

            from components.java
        }
    }
}

dependencies {
  implementation xplibs.api.core
  implementation xplibs.api.portal
  include xplibs.portal
  include xplibs.content
  include xplibs.context
  include libs.lib.thymeleaf
  include libs.lib.http.client
  include libs.lib.static
  include libs.lib.router
}

wrapper {
    gradleVersion = '9.5.0'
    distributionType = Wrapper.DistributionType.BIN
}
