# Gradle Project settings
projectName = app-matomo
version = 3.0.0

# XP App values
displayName = Matomo Analytics App
appName = no.bouvet.app.matomo
vendor = Bouvet Norge AS
vendorUrl = https://www.bouvet.no
xpVersion = 8.0.3

# Settings for publishing to a Maven repo
group = com.github.bouvet-apps
